### ISSUE TITLE
Versioned API

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/cluster-capacity#15]
The API returned on watch status should be versioned.

**Comment by ingvagabund** [comment]
Can you give an example?

**Comment by derekwaynecarr** [comment]
The watch status API represents a contract between a caller and the provider.

As a result, we should version it similar to other kube style APIs if we surface it to end-users.

One potential option would be to do something akin to the following:

```
type ClusterCapacityReview struct {
    metav1.TypeMeta
    // +optional
    api.ObjectMeta
    Spec ClusterCapacityReviewSpec
    Status ClusterCapacityReviewStatus
}

type ClusterCapacityReviewSpec struct {
    // the pod desired for scheduling
    Template api.PodTemplateSpec

    // desired number of replicas that should be scheduled
    // +optional
    Replicas *int32
}

type ClusterCapacityReviewStatus struct {    
    // actual number of replicas that could schedule
    Replicas int32
    
    // per node information about the scheduling simulation
    Nodes []ClusterCapacityReviewNodeResult
}

type ClusterCapacityReviewNodeResult struct {
    // name of node
    Name
    // number of replicas scheduled to this node
    Replicas int32
    // reason why no more pods could schedule (if any on this node)
    FailReason *ClusterCapacityReviewScheduleFailReason string
}
```

**Comment by hodovska** [comment]
@ingvagabund do you agree with this structure? - preserved scheduler fail type and message. Node fail messages are in ClusterCapacityReviewNodeResult 
 
```golang
type ClusterCapacityReview struct {
	metav1.TypeMeta
	// +optional
	api.ObjectMeta
	Spec   ClusterCapacityReviewSpec
	Status ClusterCapacityReviewStatus
}

type ClusterCapacityReviewSpec struct {
	// the pod desired for scheduling
	Template api.PodTemplateSpec

	// desired number of replicas that should be scheduled
	// +optional
	Replicas *int32
}

type ClusterCapacityReviewStatus struct {
	// actual number of replicas that could schedule
	Replicas int32

	FailReason *ClusterCapacityReviewScheduleFailReason

	// per node information about the scheduling simulation
	Nodes []ClusterCapacityReviewNodeResult
}

type ClusterCapacityReviewNodeResult struct {
	// name of node
	Name string
	// number of replicas scheduled to this node
	Replicas int32
	// reason why no more pods could schedule (if any on this node)
	FailReason string
}

type ClusterCapacityReviewScheduleFailReason struct {
	FailType    string
	FailMessage string
}
```

**Comment by ingvagabund** [comment]
LGTM

**Comment by aveshagarwal** [comment]
LGTM.

**Comment by derekwaynecarr** [comment]
this is better to me, what would happen if i want to schedule a set of pod templates?  @ingvagabund did you have a use case where you wanted to know how may of N pod templates could be scheduled together as a group?

**Comment by ingvagabund** [comment]
A sequence of pod templates is planned for another iteration of the design.

In a short, a sequence of pods is repeated indefinitely and made into a stream of pods. The scheduler just schedules items on the stream as long as it can. Once there is no pod to schedule, all the pods are broken back into sequences.  Here, two approaches how to sum the results:
1) count the total number of sequences that can be scheduled, remainder of number of pods is dropped
2) count the total number of sequences that can be scheduled, keep the remaining instances that are left

The former approach is suitable in use case where I am interested in full sequences/groups only. E.g. I want to keep a ratio of (webserves,databases,logging) in (6,2,1).  Asking how many times the given sequence/group can be scheduled.

The latter approach is suitable in use cases where I want to explore the full potential of my cluster/assigned resources. E.g. In my scenario I know a podA and podB is usually followed by podC. I am interested in how many instances of pods I can schedule, i.e. how long is the sequence (podA, podB, podC,podA, podB, podC,podA, podB, podC,...)

For the former appoach, it makes sense to refine the struct's specification. So instead of ``Template`` in ``ClusterCapacityReviewSpec`` we can specify ``[]Template``. In this case the ``Replicas``  will count a number of times a sequence/group is repeated. The same generalization will need to be done for ``Nodes``. E.g. replace ``Nodes`` with ``[]Nodes`` (or with map). So we know how many instances of each item in the sequence are scheduled to particular nodes.

In the latter case, ``Template`` is replaced with ``[]Templates``. As the templates are kept in a sequence, the total number of instances can be still stored in ``Replicas`` without a loss of how many instances or each item in a sequence are schedulable. We can apply the same reasoning for ``Nodes`` as in the former approach.

Given the current pod specification is a special case covered by the ``[]Templates`` and ``[]Nodes``, we could update the current structure to cover the future extension. 

@aveshagarwal @hodovska @derekwaynecarr any thoughts?

**Comment by derekwaynecarr** [comment]
I am wondering if the command itself rather than have a --podspec argument could just support a -f argument similar to kubectl create, and it would accept a single pod or a v1.List of pods as well.
